#! /bin/sh

# Restore wallpaper
bash $HOME/.config/bspwm/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
		let name++
	done
}
workspaces

bspc config border_width         3
bspc config window_gap           10
bspc config split_ratio          0.50

bspc config focused_border_color "#bd93f9"
bspc config normal_border_color "#282a36"
bspc config active_border_color "#bbbbbb"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox discord)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code Geany)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 \
"VirtualBox Manager")
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey conky

# Launch Conky
conky -c $HOME/.config/conky/axyl.conkyrc

# Launch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Source Code Pro Medium 10" \
-lb "#282a36FF" -lf "#f8f8f2FF" -lfr "#bd93f9FF" \
-nb "#282a36FF" -nf "#f8f8f2FF" -nfr "#bd93f9FF" \
-cb "#282a36FF" -cf "#BF616AFF" -cfr "#BF616AFF" &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Start udiskie
udiskie &

# start compositor
picom --config $HOME/.config/bspwm/picom.conf &

# replace neovim colorscheme
sed -i "s/theme =.*$/theme = \"chadracula\",/g" $HOME/.config/nvim/lua/chadrc.lua
